dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin

# Bindings configuration
java: &java
  language: java
  jdk: oraclejdk8
ruby: &ruby
  language: ruby
  rvm: 2.3.3
  jdk: oraclejdk8

# Browsers configuration
firefox: &firefox-latest
  addons: {firefox: latest}
firefox-esr: &firefox-esr
  addons: {firefox: latest-esr}
firefox-nightly: &firefox-nightly
  addons: {firefox: latest-nightly}
chrome: &chrome
  addons: {apt: {packages: [google-chrome-stable]}}

matrix:
  fast_finish: true
  exclude:
    - env: CHROME=1 TASK="calcdeps //javascript/atoms:atoms-chrome:run"
      <<: *java
      <<: *chrome
    - env: MARIONETTE=1 TASK=//java/client/test/com/thoughtworks/selenium:firefox-rc-test:run
      <<: *java
      <<: *firefox-nightly
    - env: CHROME=1 TASK=//java/client/test/com/thoughtworks/selenium:chrome-rc-test:run
      <<: *java
      <<: *chrome
    - env: CHROME=1 TASK=test_chrome
      <<: *java
      <<: *chrome
    - python: 2.7
      env: CHROME=1 TOXENV=py27-chrome
      <<: *chrome
    - python: 3.6
      env: CHROME=1 TOXENV=py36-chrome
      <<: *chrome
    - python: 2.7
      env: MARIONETTE=1 TOXENV=py27-marionette
      <<: *firefox-nightly
    - python: 3.6
      env: MARIONETTE=1 TOXENV=py36-marionette
      <<: *firefox-nightly
  include:
    - env: TASK=build
      <<: *java
    - env: TASK=//javascript/atoms:atoms
      <<: *java
    - env: TASK=//javascript/webdriver:all_js
      <<: *java
    - env: TASK=//javascript/ie-driver:atoms
      <<: *java
    - env: TASK=//javascript/chrome-driver:atoms
      <<: *java
    - env: TASK="//javascript/android-atoms:atoms ios_driver"
      <<: *java
    - env: TASK=//java/client/test/org/openqa/selenium/atoms:test:run
      <<: *java
    - env: CHROME=1 TASK="calcdeps //javascript/selenium-atoms:selenium-atoms-chrome:run"
      <<: *java
      <<: *chrome
    - env: CHROME=1 TASK="calcdeps //javascript/selenium-core:selenium-core-chrome:run"
      <<: *java
      <<: *chrome
    - env: CHROME=1 TASK="calcdeps //javascript/webdriver:webdriver-chrome:run"
      <<: *java
      <<: *chrome
    - env: TASK="calcdeps //javascript/atoms:atoms-firefox:run"
      <<: *java
      <<: *firefox-esr
    - env: MARIONETTE=1 TASK="calcdeps //javascript/webdriver:webdriver-firefox:run"
      <<: *java
      <<: *firefox-esr
    - env: TASK="calcdeps //javascript/selenium-atoms:selenium-atoms-firefox:run"
      <<: *java
      <<: *firefox-esr
    - env: TASK="calcdeps //javascript/selenium-core:selenium-core-firefox:run"
      <<: *java
      <<: *firefox-esr
    - env: TASK=test_firefox
      <<: *java
      <<: *firefox-esr
    - env: MARIONETTE=1 TASK=//java/client/test/org/openqa/selenium/firefox:marionette:run
      <<: *java
      <<: *firefox-nightly
    - env: TASK=test_java_small_tests
      <<: *java
    - env: TASK=test_grid
      <<: *java
      <<: *firefox-nightly
    - env: TASK=test_htmlunit
      <<: *java
    - env: TASK=javadocs
      <<: *java
    - language: python
      python: 2.7
      env: TOXENV=flake8
    - language: python
      python: 2.7
      env: TOXENV=docs
    - language: python
      python: 2.7
      env: TOXENV=py27-unit
    - language: python
      python: 2.7
      env: TOXENV=py27-firefox
      <<: *firefox-esr
    - language: python
      python: 2.7
      env: PHANTOMJS=1 TOXENV=py27-phantomjs
    - language: python
      python: 2.7
      env: TOXENV=py27-remote
      <<: &firefox-latest
    - language: python
      python: 3.3
      env: TOXENV=py33-unit
    - language: python
      python: 3.4
      env: TOXENV=py34-unit
    - language: python
      python: 3.5
      env: TOXENV=py35-unit
    - language: python
      python: 3.6
      env: TOXENV=flake8
    - language: python
      python: 3.6
      env: TOXENV=docs
    - language: python
      python: 3.6
      env: TOXENV=py36-unit
    - language: python
      python: 3.6
      env: TOXENV=py36-firefox
      <<: *firefox-esr
    - language: python
      python: 3.6
      env: PHANTOMJS=1 TOXENV=py36-phantomjs
    - language: python
      python: 3.6
      env: TOXENV=py36-remote
      <<: *firefox-latest
    - env: TASK=//rb:unit-test
      <<: *ruby
    - env: CHROME=1 TASK=//rb:chrome-test
      <<: *ruby
      <<: *chrome
    - env: MARIONETTE=1 TASK=//rb:firefox-test
      <<: *ruby
      <<: *firefox-latest
    - env: MARIONETTE=1 TASK=//rb:ff-nightly-test
      <<: *ruby
      <<: *firefox-nightly
    - env: TASK=//rb:ff-esr-test
      <<: *ruby
      <<: *firefox-esr
    - env: PHANTOMJS=1 TASK=//rb:phantomjs-test
      <<: *ruby
    - env: CHROME=1 TASK=//rb:remote-chrome-test
      <<: *ruby
      <<: *chrome
    - env: MARIONETTE=1 TASK=//rb:remote-firefox-test
      <<: *ruby
      <<: *firefox-latest
    - env: MARIONETTE=1 TASK=//rb:remote-ff-nightly-test
      <<: *ruby
      <<: *firefox-nightly
    - env: TASK=//rb:remote-ff-esr-test
      <<: *ruby
      <<: *firefox-esr
    - env: PHANTOMJS=1 TASK=//rb:remote-phantomjs-test
      <<: *ruby
    - env: TASK=//rb:docs
      <<: *ruby
  allow_failures:
    - env: CHROME=1 TASK=//java/client/test/com/thoughtworks/selenium:chrome-rc-test:run
    - env: MARIONETTE=1 TASK=//java/client/test/com/thoughtworks/selenium:firefox-rc-test:run
    - env: TOXENV=py27-firefox
    - env: MARIONETTE=1 TOXENV=py27-marionette
    - env: TOXENV=py27-remote
    - env: TOXENV=py36-firefox
    - env: MARIONETTE=1 TOXENV=py36-marionette
    - env: TOXENV=py36-remote
    - env: PHANTOMJS=1 TOXENV=py27-phantomjs
    - env: PHANTOMJS=1 TOXENV=py36-phantomjs
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
